# Generated by Django 2.1.7 on 2019-03-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=255)),
                ('gst_slab', models.FloatField(max_length=5)),
            ],
        ),
    ]
